server:
    port: 9000
spring:
  sql.init.mode: always
  datasource:
    url: jdbc:h2:mem:mydb
    #url: jdbc:h2:file:~/data/app
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub